### ISSUE TITLE
Wrong language shown for entity names

### ISSUE THREAD

**Issue by zehnm** [unfoldedcircle/remote-ui#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As reported in:
- https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/188

This occurs for non-english language settings. The remote UI still shows the original English name, whereas the web-configurator shows the language specific text.

Issues:
- remote UI doesn't properly check language specific strings: no fallback to main language without a country variant. For example, it only checks `de_CH` instead of also `de` if not found.
- web-configurator only stores language specific texts with language code without country variant. For example `de` instead of `de_CH`.

### How to Reproduce

1. Set language to another language than English, for example German
2. Create a remote-entity with the default name of a selected manufacturer IR dataset, e.g. `Generic TV 2 Smart Home`
3. Rename remote-entity, e.g. to `LG TV`
4. --> web-configurator shows correct name
5. --> remote-ui still shows original (English) name
6. Access the remote-entity with the REST-API to show all language strings.
   Simplified data structure:
```json
    {
        "entity_id": "uc.main.d899d6e4-ba7f-42dd-a586-1ea77b5bd8e3",
        "entity_type": "remote",
        "integration_id": "uc.main",
        "name": {
            "de": "LG TV",
            "en": "Generic TV 2 Smart Home"
        },
        "icon": "uc:remote"
    }
```

### Expected behavior

Correct language is shown with fallback to non-country specific language if the language text doesn't contain a country variant.

### UI version

0.36.0

**Comment by Pebowski** [comment]
Also when you use the rename function on the physical remote, nothing happens, the name remains the same. Maybe for the same reason.
