### ISSUE TITLE
[Bug] Deactivating an activity disables physical button navigation

### ISSUE THREAD

**Issue by wizkidweb** [unfoldedcircle/remote-ui#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After turning off an activity using the power button, the user interface can't be navigated using physical button controls.

### How to Reproduce

1. Activate an activity from the home screen using the physical buttons.
2. Deactivate the activity using the power button.
3. Attempt to navigate the user interface using the Up/Down/Left/Right and select buttons.

### Expected behavior

The active entity should be able to be highlighted and selected without touching the screen.

### UI version

0.36.1

### Additional context

I can temporarily fix this issue by tapping on the current profile, then closing it using the "X" button in the top-left.

**Comment by martonborzak** [comment]
This is fixed in the next release.
